/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class project_DataParser */

#ifndef _Included_project_DataParser
#define _Included_project_DataParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     project_DataParser
 * Method:    parseData
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_project_DataParser_parseData
  (JNIEnv *, jobject, jobject, jobject, jint, jstring, jstring, jstring, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
